### ISSUE TITLE
Plugin start failed

### ISSUE THREAD

**Issue by anssiok** [Valentin271/DeezerKodi#11]
Deezer plugin does not start at all. Was running ok last week but not anymore.

**Environment:**
LibreELEC (official): 9.2.6 (RPi4.arm)
Linux 4.19.127 #1 SMP Sat Oct 24 15:01:22 EDT 2020 armv7l GNU/Linux
Kodi (18.9 (18.9.0) Git:leia_pi4_18.9-Leia). Platform: Linux ARM 32-bit

**Log:**
```
2021-04-20 09:35:14.325 T:3011470672   ERROR: Control 52 in window 10502 has been asked to focus, but it can't
2021-04-20 09:35:14.725 T:2432152432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.deezer/addon.py", line 44, in <module>
                                                CONNECTION = Connection.load()
                                              File "/storage/.kodi/addons/plugin.audio.deezer/resources/lib/DeezerApi/__init__.py", line 110, in load
                                                cls = pickle.load(f)
                                              File "/usr/lib/python2.7/pickle.py", line 1384, in load
                                              File "/usr/lib/python2.7/pickle.py", line 864, in load
                                              File "/usr/lib/python2.7/pickle.py", line 886, in load_eof
                                            EOFError
                                            -->End of Python script error report<--
2021-04-20 09:35:14.809 T:2648908656   ERROR: GetDirectory - Error getting plugin://plugin.audio.deezer/
2021-04-20 09:35:14.824 T:3011470672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deezer/) failed
```

**Comment by Valentin271** [comment]
Hello,

Try to run `rm /storage/.kodi/temp/connection.pickle` on your Raspberry.
This should fix your issue.

**Comment by anssiok** [comment]
Yes it did. Thank you!
