### ISSUE TITLE
Fails to load credentials

### ISSUE THREAD

**Issue by OraDotNetDev** [Valentin271/DeezerKodi#16]
Apologies if this is down to my configuration.
  
**Describe the bug**  
Addon fails to launch with see "error log for details" message, correct username and password are in settings.xml for the addon.

Snippet below from the stack trace, at the end of the attached kodi log file. 
```
Traceback (most recent call last):
    File "/home/osmc/.kodi/addons/plugin.audio.deezer/addon.py", line 58, in <module>
   CONNECTION = Connection(ADDON.getSetting('username'), ADDON.getSetting('password'))
   File "/home/osmc/.kodi/addons/plugin.audio.deezer/resources/lib/DeezerApi/__init__.py", line 48, in __init__self._obtain_access_token()
```

**Environment (optional if log file provided) :**
- OS: OSMC (ARM 32-bit)
- Kodi version: 19.3 (Matrix)

**Files**  
[kodi.log](https://github.com/Valentin271/DeezerKodi/files/7960341/kodi.log)

**Comment by OraDotNetDev** [comment]
Duplicate of #13
