### ISSUE TITLE
deezer-2.0.3 does not start

### ISSUE THREAD

**Issue by batarela** [Valentin271/DeezerKodi#22]
**Describe the bug**  
Deezer Error

**Environment (optional if log file provided) :**
- OS: Windows 10 21H2, kernel: Windows NT x86 64-bit version 10.0.19044.2364
- Kodi version: Kodi (20.0-RC2 (19.90.905) Git:20221219-a184a3a7fc)

**Files**  
 Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for |: 'type' and 'type'
                                                   Traceback (most recent call last):
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\addon.py", line 8, in <module>
                                                       from app import Application, Arguments
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\__init__.py", line 5, in <module>
                                                       from .application import Application
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\application.py", line 8, in <module>
                                                       from app import routes
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\routes.py", line 4, in <module>
                                                       from app.actions import \
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\actions\__init__.py", line 5, in <module>
                                                       from .albums_actions import AlbumsActions
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\actions\albums_actions.py", line 3, in <module>
                                                       from app.views.list_view import ListView
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\views\list_view.py", line 7, in <module>
                                                       class ListView(list):
                                                     File "E:\Kodi\portable_data\addons\plugin.audio.deezer\app\views\list_view.py", line 26, in ListView
                                                       def __init__(self, view, items: dict | list):
                                                   TypeError: unsupported operand type(s) for |: 'type' and 'type'
                                                   -->End of Python script error report<--
                                                   
2023-01-03 20:05:10.736 T:2528     info <general>: CActiveAESink::OpenSink - initialize sink
2023-01-03 20:05:11.125 T:2704    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.deezer/
2023-01-03 20:05:11.135 T:4448    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deezer/) failed

**Comment by Valentin271** [comment]
Hello,

This is a quick fix, expect a new version very quickly.
