### ISSUE TITLE
Unable to request Playlist as User has no .id

### ISSUE THREAD

**Issue by JoseIgnacioTamayo** [Valentin271/DeezerKodi#7]
From the logs, running version 0.1.3

2021-02-24 08:58:33.013 T:1281315040   DEBUG: Previous line repeats 1 times.
2021-02-24 08:58:33.014 T:1281315040    INFO: DeezerKodi: Starting DeezerKodi 0.1.3
2021-02-24 08:58:33.014 T:1281315040   DEBUG: DeezerKodi: Connection: Getting connection from file /home/osmc/.kodi/temp/connection.pickle
2021-02-24 08:58:33.014 T:1281315040   DEBUG: DeezerKodi: API: Creating API instance
2021-02-24 08:58:33.014 T:1281315040    INFO: DeezerKodi: Mode 'user'
2021-02-24 08:58:33.014 T:1281315040   DEBUG: DeezerKodi: API: Getting user id me from API
2021-02-24 08:58:33.015 T:1281315040   DEBUG: DeezerKodi: Connection: Requesting user/me/ ...
2021-02-24 08:58:33.123 T:1281315040   DEBUG: DeezerKodi: Displaying user ...
2021-02-24 08:58:33.123 T:1281315040   DEBUG: DeezerKodi: Getting user's playlists
2021-02-24 08:58:33.125 T:1281315040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'User' object has no attribute 'id'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.deezer/addon.py", line 97, in <module>
                                                me.display()
                                              File "/home/osmc/.kodi/addons/plugin.audio.deezer/resources/lib/DeezerApi/__init__.py", line 364, in display
                                                for play in self.get_playlists():
                                              File "/home/osmc/.kodi/addons/plugin.audio.deezer/resources/lib/DeezerApi/__init__.py", line 248, in get_playlists
                                                playlists_data = self.connection.make_request('user', self.id, 'playlists')
                                            AttributeError: 'User' object has no attribute 'id'
                                            -->End of Python script error report<--
2021-02-24 08:58:33.125 T:1281315040   DEBUG: onExecutionDone(37, /home/osmc/.kodi/addons/plugin.audio.deezer/addon.py)
2021-02-24 08:58:33.202 T:1916559376   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-02-24 08:58:33.294 T:1281315040    INFO: Python interpreter stopped
2021-02-24 08:58:33.294 T:1281315040   DEBUG: Thread LanguageInvoker 1281315040 terminating
2021-02-24 08:58:33.296 T:1289707744   ERROR: GetDirectory - Error getting plugin://plugin.audio.deezer/?id=me&mode=user
2021-02-24 08:58:33.296 T:1289707744   DEBUG: Thread waiting 1289707744 terminating
2021-02-24 08:58:33.296 T:1916559376   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2021-02-24 08:58:33.297 T:1916559376   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deezer/?id=me&mode=user) failed
2021-02-24 08:58:33.297 T:1916559376   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.deezer/)
2021-02-24 08:58:33.297 T:1916559376   DEBUG:   ParentPath = [addons://sources/audio]
2021-02-24 08:58:33.297 T:1916559376   DEBUG: Loading items: 3, directory: plugin://plugin.audio.deezer/ sort method: 0, ascending: false
2021-02-24 08:58:33.311 T:1314885856   DEBUG: CAddonDatabase::SetLastUsed[plugin.audio.deezer] took 14 ms
2021-02-24 08:58:33.315 T:1916559376   DEBUG: RetrieveMusicInfo() took 0 msec

**Comment by JoseIgnacioTamayo** [comment]
Hum.... I had to remove the file /home/osmc/.kodi/temp/connection.pickle, apparently, to have a new connection and token setup.

Maybe it is worth checking that the connection loaded from the temp file works.

**Comment by Valentin271** [comment]
Hello,

Did you changed the logged in account at any time ?
Is it working again after deleting connection.pickle ?

Valentin
